### ISSUE TITLE
Expand Onboarding Page

### ISSUE THREAD

**Issue by shawnericksen** [QuantumRangers-SE-Team-10/lasertech#15]
We are going to split up the form for simplicity into a player form (small box above existing form) and roster form (current form's layout)

### Features
- Add small box above the main form to add players.
  - Takes playerID and codename
  - codename will become not enterable until playerID has been queried (see #19 )
  - Has two submit buttons to add player to red team or green team roster form.
- Roster Form
  - Add third column to roster form to main forms for each team to be the equimentId intake.
  - First and Second column (playerID and codename) in main field will be autofilled when Player form is submitted.
  - For equipmentIds, red ids are odd and green ids are even, this should be validated by the form.

Return of the entire roster form is roughly expected to look like such:
```yaml
{
  playerSessions: [
    {
      playerID: 1,
      codename: 'billy bob joe',
      equipmentId: 11,
      team: 'Red',
    },
    {
      playerID: 2,
      codename: 'Joe Biden',
      equipmentId: 14,
      team: 'Green',
    },
    ...
  ],
}
```
